# -*- coding: utf-8 -*-
"""Qr_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tjSEwLMry_6g5_Jt96X4yFwZ-DMnsllP
"""

pip install qrcode[pil]

import qrcode

url = input("Enter the URL: ").strip()

file_path = "qrcode.png"

qr = qrcode.QRCode()
qr.add_data(url)

img  = qr.make_image()
img.save(file_path)

from google.colab import files

files.download('qrcode.png')

print("and All set 👍")